formatter: markdown table

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
    {{ .Content }}
    <!-- END_AUTOMATED_TF_DOCS_BLOCK -->

sections:
  show:
    - inputs
    - outputs
    - providers
    - resources
    - data-sources

content: |-
  ## Description
  Basic example of how to create an event grid system topic

  ## Example Usage
  Basic usage of this module is as follows:

  {{- $providers := include "providers.tf" }}
  {{ if $providers }}
  ### providers.tf
  ```hcl
  {{ $providers }}
  ```
  {{ end }}

  {{- $data := include "data.tf" }}
  {{ if $data }}
  ### data.tf
  ```hcl
  {{ $data }}
  ```
  {{ end }}

  {{- $locals := include "locals.tf" }}
  {{ if $locals }}
  ### locals.tf
  ```hcl
  {{ $locals }}
  ```
  {{ end }}

  {{- $main := include "main.tf" }}
  {{ if $main }}
  ### main.tf
  ```hcl
  {{ $main }}
  ```
  {{ end }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

sort:
    enabled: true
    by: required
